package com.linxonline.mallet.input ;

public enum InputType
{
	NONE,
	MOUSE_MOVED,
	MOUSE1_PRESSED, MOUSE1_RELEASED,
	MOUSE2_PRESSED, MOUSE2_RELEASED,
	SCROLL_WHEEL,
	KEYBOARD_PRESSED, KEYBOARD_RELEASED,
	TOUCH_MOVE, TOUCH_UP, TOUCH_DOWN ;
}