#! /bin/bash

# Find Jars in Jar folder - JOGL, etc..
for i in `ls ./libs/*.jar`
do
  CLASSPATH=${CLASSPATH}:${i}
done

java --module-path $CLASSPATH -XX:MinHeapFreeRatio=1 -XX:MaxHeapFreeRatio=5 -Dsun.awt.noerasebackground=true -Dsun.java2d.noddraw=true --module MalletEngine/com.linxonline.mallet.core.desktop.DesktopTestMain $@
