#! /bin/bash

# Find Jars in root directory
for i in `ls ./*.jar`
do
  CLASSPATH=${CLASSPATH}:${i}
done

# Find Jars in Jar folder - JOGL, etc..
for i in `ls ./libs/*.jar`
do
  CLASSPATH=${CLASSPATH}:${i}
done

java -classpath $CLASSPATH template.main.desktop.Main $@
#java -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n -classpath $CLASSPATH com.linxonline.mallet.main.Main $@
